### ISSUE TITLE
Not compatible with Fedora 35 / Gnome 41

### ISSUE THREAD

**Issue by snickl** [darkretailer/gnome-shell-extension_maxi#2]
Shows as "outdated", probably just needs a version bump.

Love this extension and really miss it btw!

**Comment by PhilDevProg** [comment]
It unfortunately seems like this extension has been abandoned... And with GNOME 45, someone would have to adapt the extension to[ the new import system](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm) so a little version bump isn't enough.

**Comment by snickl** [comment]
> It unfortunately seems like this extension has been abandoned... And with GNOME 45, someone would have to adapt the extension to[ the new import system](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm) so a little version bump isn't enough.

Yeah I created [this fork](https://github.com/snickl/gnome-shell-extension_maxi) where I got the vertical maximizing working again, but the preferences dialog is a much harder nut to crack. Since vertical maximizing of all windows is all I want from this extension, it's unlikely that I will tackle that.
